name: Seat Checker


on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:


jobs:

  check:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install dependencies
        run: |
          pip install requests


      - name: Run seat checker
        env:
          CINEMA_COOKIES: ${{ secrets.CINEMA_COOKIES }}
          CINEMA_UUID: ${{ secrets.CINEMA_UUID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: |
          python seat_checker.py


      - name: Save seats state
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add seats_state.json

          git diff --cached --quiet || git commit -m "Update seats checker state"

          git push
